// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/shadowgame/rpg/modules/protocol/dto/ResponseDto.proto

package com.shadowgame.rpg.modules.protocol.dto;

public final class ResponseDto$$Gen {
  private ResponseDto$$Gen() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResponseDtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 sn = 1;
    /**
     * <code>optional int32 sn = 1;</code>
     *
     * <pre>
     **
     * 序号
     * </pre>
     */
    boolean hasSn();
    /**
     * <code>optional int32 sn = 1;</code>
     *
     * <pre>
     **
     * 序号
     * </pre>
     */
    int getSn();

    // optional bool isError = 2;
    /**
     * <code>optional bool isError = 2;</code>
     *
     * <pre>
     **
     * 是否是错误响应
     * </pre>
     */
    boolean hasIsError();
    /**
     * <code>optional bool isError = 2;</code>
     *
     * <pre>
     **
     * 是否是错误响应
     * </pre>
     */
    boolean getIsError();

    // optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
     *
     * <pre>
     **
     * 响应结果dto
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
     *
     * <pre>
     **
     * 响应结果dto
     * </pre>
     */
    com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto getResult();
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
     *
     * <pre>
     **
     * 响应结果dto
     * </pre>
     */
    com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDtoOrBuilder getResultOrBuilder();
  }
  /**
   * Protobuf type {@code com.shadowgame.rpg.modules.protocol.dto.ResponseDto}
   */
  public static final class ResponseDto extends
      com.google.protobuf.GeneratedMessage
      implements ResponseDtoOrBuilder {
    // Use ResponseDto.newBuilder() to construct.
    private ResponseDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResponseDto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResponseDto defaultInstance;
    public static ResponseDto getDefaultInstance() {
      return defaultInstance;
    }

    public ResponseDto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sn_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isError_ = input.readBool();
              break;
            }
            case 26: {
              com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.internal_static_com_shadowgame_rpg_modules_protocol_dto_ResponseDto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.internal_static_com_shadowgame_rpg_modules_protocol_dto_ResponseDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto.class, com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto.Builder.class);
    }

    public static com.google.protobuf.Parser<ResponseDto> PARSER =
        new com.google.protobuf.AbstractParser<ResponseDto>() {
      public ResponseDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseDto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseDto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 sn = 1;
    public static final int SN_FIELD_NUMBER = 1;
    private int sn_;
    /**
     * <code>optional int32 sn = 1;</code>
     *
     * <pre>
     **
     * 序号
     * </pre>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 sn = 1;</code>
     *
     * <pre>
     **
     * 序号
     * </pre>
     */
    public int getSn() {
      return sn_;
    }

    // optional bool isError = 2;
    public static final int ISERROR_FIELD_NUMBER = 2;
    private boolean isError_;
    /**
     * <code>optional bool isError = 2;</code>
     *
     * <pre>
     **
     * 是否是错误响应
     * </pre>
     */
    public boolean hasIsError() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool isError = 2;</code>
     *
     * <pre>
     **
     * 是否是错误响应
     * </pre>
     */
    public boolean getIsError() {
      return isError_;
    }

    // optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;
    public static final int RESULT_FIELD_NUMBER = 3;
    private com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto result_;
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
     *
     * <pre>
     **
     * 响应结果dto
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
     *
     * <pre>
     **
     * 响应结果dto
     * </pre>
     */
    public com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto getResult() {
      return result_;
    }
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
     *
     * <pre>
     **
     * 响应结果dto
     * </pre>
     */
    public com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDtoOrBuilder getResultOrBuilder() {
      return result_;
    }

    private void initFields() {
      sn_ = 0;
      isError_ = false;
      result_ = com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sn_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isError_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sn_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isError_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.shadowgame.rpg.modules.protocol.dto.ResponseDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.internal_static_com_shadowgame_rpg_modules_protocol_dto_ResponseDto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.internal_static_com_shadowgame_rpg_modules_protocol_dto_ResponseDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto.class, com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto.Builder.class);
      }

      // Construct using com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        isError_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (resultBuilder_ == null) {
          result_ = com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.getDefaultInstance();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.internal_static_com_shadowgame_rpg_modules_protocol_dto_ResponseDto_descriptor;
      }

      public com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto getDefaultInstanceForType() {
        return com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto.getDefaultInstance();
      }

      public com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto build() {
        com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto buildPartial() {
        com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto result = new com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sn_ = sn_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isError_ = isError_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto) {
          return mergeFrom((com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto other) {
        if (other == com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto.getDefaultInstance()) return this;
        if (other.hasSn()) {
          setSn(other.getSn());
        }
        if (other.hasIsError()) {
          setIsError(other.getIsError());
        }
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shadowgame.rpg.modules.protocol.dto.ResponseDto$$Gen.ResponseDto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 sn = 1;
      private int sn_ ;
      /**
       * <code>optional int32 sn = 1;</code>
       *
       * <pre>
       **
       * 序号
       * </pre>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 sn = 1;</code>
       *
       * <pre>
       **
       * 序号
       * </pre>
       */
      public int getSn() {
        return sn_;
      }
      /**
       * <code>optional int32 sn = 1;</code>
       *
       * <pre>
       **
       * 序号
       * </pre>
       */
      public Builder setSn(int value) {
        bitField0_ |= 0x00000001;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sn = 1;</code>
       *
       * <pre>
       **
       * 序号
       * </pre>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sn_ = 0;
        onChanged();
        return this;
      }

      // optional bool isError = 2;
      private boolean isError_ ;
      /**
       * <code>optional bool isError = 2;</code>
       *
       * <pre>
       **
       * 是否是错误响应
       * </pre>
       */
      public boolean hasIsError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool isError = 2;</code>
       *
       * <pre>
       **
       * 是否是错误响应
       * </pre>
       */
      public boolean getIsError() {
        return isError_;
      }
      /**
       * <code>optional bool isError = 2;</code>
       *
       * <pre>
       **
       * 是否是错误响应
       * </pre>
       */
      public Builder setIsError(boolean value) {
        bitField0_ |= 0x00000002;
        isError_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isError = 2;</code>
       *
       * <pre>
       **
       * 是否是错误响应
       * </pre>
       */
      public Builder clearIsError() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isError_ = false;
        onChanged();
        return this;
      }

      // optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;
      private com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto result_ = com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto, com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.Builder, com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDtoOrBuilder> resultBuilder_;
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
       *
       * <pre>
       **
       * 响应结果dto
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
       *
       * <pre>
       **
       * 响应结果dto
       * </pre>
       */
      public com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto getResult() {
        if (resultBuilder_ == null) {
          return result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
       *
       * <pre>
       **
       * 响应结果dto
       * </pre>
       */
      public Builder setResult(com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
       *
       * <pre>
       **
       * 响应结果dto
       * </pre>
       */
      public Builder setResult(
          com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
       *
       * <pre>
       **
       * 响应结果dto
       * </pre>
       */
      public Builder mergeResult(com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              result_ != com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.getDefaultInstance()) {
            result_ =
              com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
       *
       * <pre>
       **
       * 响应结果dto
       * </pre>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.getDefaultInstance();
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
       *
       * <pre>
       **
       * 响应结果dto
       * </pre>
       */
      public com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.Builder getResultBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
       *
       * <pre>
       **
       * 响应结果dto
       * </pre>
       */
      public com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDtoOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_;
        }
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.ProtobufDto result = 3;</code>
       *
       * <pre>
       **
       * 响应结果dto
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto, com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.Builder, com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDtoOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto, com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDto.Builder, com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.ProtobufDtoOrBuilder>(
                  result_,
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.shadowgame.rpg.modules.protocol.dto.ResponseDto)
    }

    static {
      defaultInstance = new ResponseDto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.shadowgame.rpg.modules.protocol.dto.ResponseDto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadowgame_rpg_modules_protocol_dto_ResponseDto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_shadowgame_rpg_modules_protocol_dto_ResponseDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9com/shadowgame/rpg/modules/protocol/dt" +
      "o/ResponseDto.proto\022\'com.shadowgame.rpg." +
      "modules.protocol.dto\0329com/shadowgame/rpg" +
      "/modules/protocol/dto/ProtobufDto.proto\"" +
      "p\n\013ResponseDto\022\n\n\002sn\030\001 \001(\005\022\017\n\007isError\030\002 " +
      "\001(\010\022D\n\006result\030\003 \001(\01324.com.shadowgame.rpg" +
      ".modules.protocol.dto.ProtobufDtoB\022B\020Res" +
      "ponseDto$$Gen"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_shadowgame_rpg_modules_protocol_dto_ResponseDto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_shadowgame_rpg_modules_protocol_dto_ResponseDto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_shadowgame_rpg_modules_protocol_dto_ResponseDto_descriptor,
              new java.lang.String[] { "Sn", "IsError", "Result", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.shadowgame.rpg.modules.protocol.dto.ProtobufDto$$Gen.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
