// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/shadowgame/rpg/modules/protocol/dto/generals/GeneralsDto_PROTO.proto

package com.shadowgame.rpg.modules.protobuf.dto.generals;

public final class GeneralsDtoPROTO {
  private GeneralsDtoPROTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GeneralsDtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 id = 1;
    /**
     * <code>optional int64 id = 1;</code>
     *
     * <pre>
     **
     * 武将id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     *
     * <pre>
     **
     * 武将id
     * </pre>
     */
    long getId();

    // optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
     *
     * <pre>
     **
     * 家将基本信息
     * </pre>
     */
    boolean hasGeneralsSimple();
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
     *
     * <pre>
     **
     * 家将基本信息
     * </pre>
     */
    com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto getGeneralsSimple();
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
     *
     * <pre>
     **
     * 家将基本信息
     * </pre>
     */
    com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDtoOrBuilder getGeneralsSimpleOrBuilder();

    // optional int32 army = 3;
    /**
     * <code>optional int32 army = 3;</code>
     *
     * <pre>
     **
     * 部队星级
     * </pre>
     */
    boolean hasArmy();
    /**
     * <code>optional int32 army = 3;</code>
     *
     * <pre>
     **
     * 部队星级
     * </pre>
     */
    int getArmy();

    // optional int32 skillId = 4;
    /**
     * <code>optional int32 skillId = 4;</code>
     *
     * <pre>
     **
     * 战法id
     * </pre>
     */
    boolean hasSkillId();
    /**
     * <code>optional int32 skillId = 4;</code>
     *
     * <pre>
     **
     * 战法id
     * </pre>
     */
    int getSkillId();

    // optional int32 tong = 5;
    /**
     * <code>optional int32 tong = 5;</code>
     *
     * <pre>
     **
     * 统
     * </pre>
     */
    boolean hasTong();
    /**
     * <code>optional int32 tong = 5;</code>
     *
     * <pre>
     **
     * 统
     * </pre>
     */
    int getTong();

    // optional int32 yong = 6;
    /**
     * <code>optional int32 yong = 6;</code>
     *
     * <pre>
     **
     * 勇
     * </pre>
     */
    boolean hasYong();
    /**
     * <code>optional int32 yong = 6;</code>
     *
     * <pre>
     **
     * 勇
     * </pre>
     */
    int getYong();

    // optional int32 zhi = 7;
    /**
     * <code>optional int32 zhi = 7;</code>
     *
     * <pre>
     **
     * 智
     * </pre>
     */
    boolean hasZhi();
    /**
     * <code>optional int32 zhi = 7;</code>
     *
     * <pre>
     **
     * 智
     * </pre>
     */
    int getZhi();

    // optional int32 position = 8;
    /**
     * <code>optional int32 position = 8;</code>
     *
     * <pre>
     **
     * 阵中位置
     * </pre>
     */
    boolean hasPosition();
    /**
     * <code>optional int32 position = 8;</code>
     *
     * <pre>
     **
     * 阵中位置
     * </pre>
     */
    int getPosition();
  }
  /**
   * Protobuf type {@code com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto}
   *
   * <pre>
   **
   * 武将dto
   * @author wcj10051891@gmail.com
   *字段列表:
   * //武将id
   *long id
   * //家将基本信息
   *com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple
   * //部队星级
   *int army
   * //战法id
   *int skillId
   * //统
   *int tong
   * //勇
   *int yong
   * //智
   *int zhi
   * //阵中位置
   *int position
   * </pre>
   */
  public static final class GeneralsDto extends
      com.google.protobuf.GeneratedMessage
      implements GeneralsDtoOrBuilder {
    // Use GeneralsDto.newBuilder() to construct.
    private GeneralsDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GeneralsDto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GeneralsDto defaultInstance;
    public static GeneralsDto getDefaultInstance() {
      return defaultInstance;
    }

    public GeneralsDto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GeneralsDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = generalsSimple_.toBuilder();
              }
              generalsSimple_ = input.readMessage(com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(generalsSimple_);
                generalsSimple_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              army_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              skillId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              tong_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              yong_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              zhi_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              position_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_generals_GeneralsDto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_generals_GeneralsDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.class, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.Builder.class);
    }

    public static com.google.protobuf.Parser<GeneralsDto> PARSER =
        new com.google.protobuf.AbstractParser<GeneralsDto>() {
      public GeneralsDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GeneralsDto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GeneralsDto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     *
     * <pre>
     **
     * 武将id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     *
     * <pre>
     **
     * 武将id
     * </pre>
     */
    public long getId() {
      return id_;
    }

    // optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;
    public static final int GENERALSSIMPLE_FIELD_NUMBER = 2;
    private com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto generalsSimple_;
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
     *
     * <pre>
     **
     * 家将基本信息
     * </pre>
     */
    public boolean hasGeneralsSimple() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
     *
     * <pre>
     **
     * 家将基本信息
     * </pre>
     */
    public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto getGeneralsSimple() {
      return generalsSimple_;
    }
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
     *
     * <pre>
     **
     * 家将基本信息
     * </pre>
     */
    public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDtoOrBuilder getGeneralsSimpleOrBuilder() {
      return generalsSimple_;
    }

    // optional int32 army = 3;
    public static final int ARMY_FIELD_NUMBER = 3;
    private int army_;
    /**
     * <code>optional int32 army = 3;</code>
     *
     * <pre>
     **
     * 部队星级
     * </pre>
     */
    public boolean hasArmy() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 army = 3;</code>
     *
     * <pre>
     **
     * 部队星级
     * </pre>
     */
    public int getArmy() {
      return army_;
    }

    // optional int32 skillId = 4;
    public static final int SKILLID_FIELD_NUMBER = 4;
    private int skillId_;
    /**
     * <code>optional int32 skillId = 4;</code>
     *
     * <pre>
     **
     * 战法id
     * </pre>
     */
    public boolean hasSkillId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 skillId = 4;</code>
     *
     * <pre>
     **
     * 战法id
     * </pre>
     */
    public int getSkillId() {
      return skillId_;
    }

    // optional int32 tong = 5;
    public static final int TONG_FIELD_NUMBER = 5;
    private int tong_;
    /**
     * <code>optional int32 tong = 5;</code>
     *
     * <pre>
     **
     * 统
     * </pre>
     */
    public boolean hasTong() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 tong = 5;</code>
     *
     * <pre>
     **
     * 统
     * </pre>
     */
    public int getTong() {
      return tong_;
    }

    // optional int32 yong = 6;
    public static final int YONG_FIELD_NUMBER = 6;
    private int yong_;
    /**
     * <code>optional int32 yong = 6;</code>
     *
     * <pre>
     **
     * 勇
     * </pre>
     */
    public boolean hasYong() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 yong = 6;</code>
     *
     * <pre>
     **
     * 勇
     * </pre>
     */
    public int getYong() {
      return yong_;
    }

    // optional int32 zhi = 7;
    public static final int ZHI_FIELD_NUMBER = 7;
    private int zhi_;
    /**
     * <code>optional int32 zhi = 7;</code>
     *
     * <pre>
     **
     * 智
     * </pre>
     */
    public boolean hasZhi() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 zhi = 7;</code>
     *
     * <pre>
     **
     * 智
     * </pre>
     */
    public int getZhi() {
      return zhi_;
    }

    // optional int32 position = 8;
    public static final int POSITION_FIELD_NUMBER = 8;
    private int position_;
    /**
     * <code>optional int32 position = 8;</code>
     *
     * <pre>
     **
     * 阵中位置
     * </pre>
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 position = 8;</code>
     *
     * <pre>
     **
     * 阵中位置
     * </pre>
     */
    public int getPosition() {
      return position_;
    }

    private void initFields() {
      id_ = 0L;
      generalsSimple_ = com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.getDefaultInstance();
      army_ = 0;
      skillId_ = 0;
      tong_ = 0;
      yong_ = 0;
      zhi_ = 0;
      position_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, generalsSimple_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, army_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, skillId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, tong_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, yong_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, zhi_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, position_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, generalsSimple_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, army_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, skillId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, tong_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, yong_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, zhi_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, position_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto}
     *
     * <pre>
     **
     * 武将dto
     * @author wcj10051891@gmail.com
     *字段列表:
     * //武将id
     *long id
     * //家将基本信息
     *com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple
     * //部队星级
     *int army
     * //战法id
     *int skillId
     * //统
     *int tong
     * //勇
     *int yong
     * //智
     *int zhi
     * //阵中位置
     *int position
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_generals_GeneralsDto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_generals_GeneralsDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.class, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.Builder.class);
      }

      // Construct using com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGeneralsSimpleFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (generalsSimpleBuilder_ == null) {
          generalsSimple_ = com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.getDefaultInstance();
        } else {
          generalsSimpleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        army_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        skillId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        tong_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        yong_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        zhi_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        position_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_generals_GeneralsDto_descriptor;
      }

      public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto getDefaultInstanceForType() {
        return com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.getDefaultInstance();
      }

      public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto build() {
        com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto buildPartial() {
        com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto result = new com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (generalsSimpleBuilder_ == null) {
          result.generalsSimple_ = generalsSimple_;
        } else {
          result.generalsSimple_ = generalsSimpleBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.army_ = army_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.skillId_ = skillId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.tong_ = tong_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.yong_ = yong_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.zhi_ = zhi_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.position_ = position_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto) {
          return mergeFrom((com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto other) {
        if (other == com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasGeneralsSimple()) {
          mergeGeneralsSimple(other.getGeneralsSimple());
        }
        if (other.hasArmy()) {
          setArmy(other.getArmy());
        }
        if (other.hasSkillId()) {
          setSkillId(other.getSkillId());
        }
        if (other.hasTong()) {
          setTong(other.getTong());
        }
        if (other.hasYong()) {
          setYong(other.getYong());
        }
        if (other.hasZhi()) {
          setZhi(other.getZhi());
        }
        if (other.hasPosition()) {
          setPosition(other.getPosition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 id = 1;
      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       *
       * <pre>
       **
       * 武将id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       *
       * <pre>
       **
       * 武将id
       * </pre>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       *
       * <pre>
       **
       * 武将id
       * </pre>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       *
       * <pre>
       **
       * 武将id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;
      private com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto generalsSimple_ = com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.Builder, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDtoOrBuilder> generalsSimpleBuilder_;
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
       *
       * <pre>
       **
       * 家将基本信息
       * </pre>
       */
      public boolean hasGeneralsSimple() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
       *
       * <pre>
       **
       * 家将基本信息
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto getGeneralsSimple() {
        if (generalsSimpleBuilder_ == null) {
          return generalsSimple_;
        } else {
          return generalsSimpleBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
       *
       * <pre>
       **
       * 家将基本信息
       * </pre>
       */
      public Builder setGeneralsSimple(com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto value) {
        if (generalsSimpleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          generalsSimple_ = value;
          onChanged();
        } else {
          generalsSimpleBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
       *
       * <pre>
       **
       * 家将基本信息
       * </pre>
       */
      public Builder setGeneralsSimple(
          com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.Builder builderForValue) {
        if (generalsSimpleBuilder_ == null) {
          generalsSimple_ = builderForValue.build();
          onChanged();
        } else {
          generalsSimpleBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
       *
       * <pre>
       **
       * 家将基本信息
       * </pre>
       */
      public Builder mergeGeneralsSimple(com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto value) {
        if (generalsSimpleBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              generalsSimple_ != com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.getDefaultInstance()) {
            generalsSimple_ =
              com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.newBuilder(generalsSimple_).mergeFrom(value).buildPartial();
          } else {
            generalsSimple_ = value;
          }
          onChanged();
        } else {
          generalsSimpleBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
       *
       * <pre>
       **
       * 家将基本信息
       * </pre>
       */
      public Builder clearGeneralsSimple() {
        if (generalsSimpleBuilder_ == null) {
          generalsSimple_ = com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.getDefaultInstance();
          onChanged();
        } else {
          generalsSimpleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
       *
       * <pre>
       **
       * 家将基本信息
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.Builder getGeneralsSimpleBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getGeneralsSimpleFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
       *
       * <pre>
       **
       * 家将基本信息
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDtoOrBuilder getGeneralsSimpleOrBuilder() {
        if (generalsSimpleBuilder_ != null) {
          return generalsSimpleBuilder_.getMessageOrBuilder();
        } else {
          return generalsSimple_;
        }
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsSimpleDto generalsSimple = 2;</code>
       *
       * <pre>
       **
       * 家将基本信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.Builder, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDtoOrBuilder> 
          getGeneralsSimpleFieldBuilder() {
        if (generalsSimpleBuilder_ == null) {
          generalsSimpleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDto.Builder, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.GeneralsSimpleDtoOrBuilder>(
                  generalsSimple_,
                  getParentForChildren(),
                  isClean());
          generalsSimple_ = null;
        }
        return generalsSimpleBuilder_;
      }

      // optional int32 army = 3;
      private int army_ ;
      /**
       * <code>optional int32 army = 3;</code>
       *
       * <pre>
       **
       * 部队星级
       * </pre>
       */
      public boolean hasArmy() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 army = 3;</code>
       *
       * <pre>
       **
       * 部队星级
       * </pre>
       */
      public int getArmy() {
        return army_;
      }
      /**
       * <code>optional int32 army = 3;</code>
       *
       * <pre>
       **
       * 部队星级
       * </pre>
       */
      public Builder setArmy(int value) {
        bitField0_ |= 0x00000004;
        army_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 army = 3;</code>
       *
       * <pre>
       **
       * 部队星级
       * </pre>
       */
      public Builder clearArmy() {
        bitField0_ = (bitField0_ & ~0x00000004);
        army_ = 0;
        onChanged();
        return this;
      }

      // optional int32 skillId = 4;
      private int skillId_ ;
      /**
       * <code>optional int32 skillId = 4;</code>
       *
       * <pre>
       **
       * 战法id
       * </pre>
       */
      public boolean hasSkillId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 skillId = 4;</code>
       *
       * <pre>
       **
       * 战法id
       * </pre>
       */
      public int getSkillId() {
        return skillId_;
      }
      /**
       * <code>optional int32 skillId = 4;</code>
       *
       * <pre>
       **
       * 战法id
       * </pre>
       */
      public Builder setSkillId(int value) {
        bitField0_ |= 0x00000008;
        skillId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 skillId = 4;</code>
       *
       * <pre>
       **
       * 战法id
       * </pre>
       */
      public Builder clearSkillId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        skillId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 tong = 5;
      private int tong_ ;
      /**
       * <code>optional int32 tong = 5;</code>
       *
       * <pre>
       **
       * 统
       * </pre>
       */
      public boolean hasTong() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 tong = 5;</code>
       *
       * <pre>
       **
       * 统
       * </pre>
       */
      public int getTong() {
        return tong_;
      }
      /**
       * <code>optional int32 tong = 5;</code>
       *
       * <pre>
       **
       * 统
       * </pre>
       */
      public Builder setTong(int value) {
        bitField0_ |= 0x00000010;
        tong_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tong = 5;</code>
       *
       * <pre>
       **
       * 统
       * </pre>
       */
      public Builder clearTong() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tong_ = 0;
        onChanged();
        return this;
      }

      // optional int32 yong = 6;
      private int yong_ ;
      /**
       * <code>optional int32 yong = 6;</code>
       *
       * <pre>
       **
       * 勇
       * </pre>
       */
      public boolean hasYong() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 yong = 6;</code>
       *
       * <pre>
       **
       * 勇
       * </pre>
       */
      public int getYong() {
        return yong_;
      }
      /**
       * <code>optional int32 yong = 6;</code>
       *
       * <pre>
       **
       * 勇
       * </pre>
       */
      public Builder setYong(int value) {
        bitField0_ |= 0x00000020;
        yong_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 yong = 6;</code>
       *
       * <pre>
       **
       * 勇
       * </pre>
       */
      public Builder clearYong() {
        bitField0_ = (bitField0_ & ~0x00000020);
        yong_ = 0;
        onChanged();
        return this;
      }

      // optional int32 zhi = 7;
      private int zhi_ ;
      /**
       * <code>optional int32 zhi = 7;</code>
       *
       * <pre>
       **
       * 智
       * </pre>
       */
      public boolean hasZhi() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 zhi = 7;</code>
       *
       * <pre>
       **
       * 智
       * </pre>
       */
      public int getZhi() {
        return zhi_;
      }
      /**
       * <code>optional int32 zhi = 7;</code>
       *
       * <pre>
       **
       * 智
       * </pre>
       */
      public Builder setZhi(int value) {
        bitField0_ |= 0x00000040;
        zhi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 zhi = 7;</code>
       *
       * <pre>
       **
       * 智
       * </pre>
       */
      public Builder clearZhi() {
        bitField0_ = (bitField0_ & ~0x00000040);
        zhi_ = 0;
        onChanged();
        return this;
      }

      // optional int32 position = 8;
      private int position_ ;
      /**
       * <code>optional int32 position = 8;</code>
       *
       * <pre>
       **
       * 阵中位置
       * </pre>
       */
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 position = 8;</code>
       *
       * <pre>
       **
       * 阵中位置
       * </pre>
       */
      public int getPosition() {
        return position_;
      }
      /**
       * <code>optional int32 position = 8;</code>
       *
       * <pre>
       **
       * 阵中位置
       * </pre>
       */
      public Builder setPosition(int value) {
        bitField0_ |= 0x00000080;
        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 position = 8;</code>
       *
       * <pre>
       **
       * 阵中位置
       * </pre>
       */
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00000080);
        position_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto)
    }

    static {
      defaultInstance = new GeneralsDto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadowgame_rpg_modules_protocol_dto_generals_GeneralsDto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_shadowgame_rpg_modules_protocol_dto_generals_GeneralsDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nHcom/shadowgame/rpg/modules/protocol/dt" +
      "o/generals/GeneralsDto_PROTO.proto\0220com." +
      "shadowgame.rpg.modules.protocol.dto.gene" +
      "rals\032Ncom/shadowgame/rpg/modules/protoco" +
      "l/dto/generals/GeneralsSimpleDto_PROTO.p" +
      "roto\"\320\001\n\013GeneralsDto\022\n\n\002id\030\001 \001(\003\022[\n\016gene" +
      "ralsSimple\030\002 \001(\0132C.com.shadowgame.rpg.mo" +
      "dules.protocol.dto.generals.GeneralsSimp" +
      "leDto\022\014\n\004army\030\003 \001(\005\022\017\n\007skillId\030\004 \001(\005\022\014\n\004" +
      "tong\030\005 \001(\005\022\014\n\004yong\030\006 \001(\005\022\013\n\003zhi\030\007 \001(\005\022\020\n",
      "\010position\030\010 \001(\005B2\n0com.shadowgame.rpg.mo" +
      "dules.protobuf.dto.generals"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_shadowgame_rpg_modules_protocol_dto_generals_GeneralsDto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_shadowgame_rpg_modules_protocol_dto_generals_GeneralsDto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_shadowgame_rpg_modules_protocol_dto_generals_GeneralsDto_descriptor,
              new java.lang.String[] { "Id", "GeneralsSimple", "Army", "SkillId", "Tong", "Yong", "Zhi", "Position", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsSimpleDtoPROTO.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
