//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto-out/com/shadowgame/rpg/msg/LoginMsg.proto
namespace com.shadowgame.rpg.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginMsg")]
  public partial class LoginMsg : global::ProtoBuf.IExtensible
  {
    public LoginMsg() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private readonly global::System.Collections.Generic.List<com.shadowgame.rpg.msg.NoticeMsg> _msgs1 = new global::System.Collections.Generic.List<com.shadowgame.rpg.msg.NoticeMsg>();
    [global::ProtoBuf.ProtoMember(3, Name=@"msgs1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.shadowgame.rpg.msg.NoticeMsg> msgs1
    {
      get { return _msgs1; }
    }
  
    private readonly global::System.Collections.Generic.List<com.shadowgame.rpg.msg.AlertMsg> _msgs2 = new global::System.Collections.Generic.List<com.shadowgame.rpg.msg.AlertMsg>();
    [global::ProtoBuf.ProtoMember(4, Name=@"msgs2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.shadowgame.rpg.msg.AlertMsg> msgs2
    {
      get { return _msgs2; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NoticeMsg")]
  public partial class NoticeMsg : global::ProtoBuf.IExtensible
  {
    public NoticeMsg() {}
    
    private string _content = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AlertMsg")]
  public partial class AlertMsg : global::ProtoBuf.IExtensible
  {
    public AlertMsg() {}
    
    private string _content = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}