// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/shadowgame/rpg/modules/protocol/dto/chat/ChatDto_PROTO.proto

package com.shadowgame.rpg.modules.protobuf.dto.chat;

public final class ChatDtoPROTO {
  private ChatDtoPROTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatDtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 sayerId = 1;
    /**
     * <code>optional int64 sayerId = 1;</code>
     *
     * <pre>
     **
     * 发言者id
     * </pre>
     */
    boolean hasSayerId();
    /**
     * <code>optional int64 sayerId = 1;</code>
     *
     * <pre>
     **
     * 发言者id
     * </pre>
     */
    long getSayerId();

    // optional string sayerNickname = 2;
    /**
     * <code>optional string sayerNickname = 2;</code>
     *
     * <pre>
     **
     * 发言者昵称
     * </pre>
     */
    boolean hasSayerNickname();
    /**
     * <code>optional string sayerNickname = 2;</code>
     *
     * <pre>
     **
     * 发言者昵称
     * </pre>
     */
    java.lang.String getSayerNickname();
    /**
     * <code>optional string sayerNickname = 2;</code>
     *
     * <pre>
     **
     * 发言者昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getSayerNicknameBytes();

    // optional string content = 3;
    /**
     * <code>optional string content = 3;</code>
     *
     * <pre>
     **
     * 发言内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 3;</code>
     *
     * <pre>
     **
     * 发言内容
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 3;</code>
     *
     * <pre>
     **
     * 发言内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code com.shadowgame.rpg.modules.protocol.dto.chat.ChatDto}
   *
   * <pre>
   **
   * 聊天dto
   * @author wcj10051891@gmail.com
   *字段列表:
   * //发言者id
   *java.lang.Long sayerId
   * //发言者昵称
   *java.lang.String sayerNickname
   * //发言内容
   *java.lang.String content
   * </pre>
   */
  public static final class ChatDto extends
      com.google.protobuf.GeneratedMessage
      implements ChatDtoOrBuilder {
    // Use ChatDto.newBuilder() to construct.
    private ChatDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatDto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatDto defaultInstance;
    public static ChatDto getDefaultInstance() {
      return defaultInstance;
    }

    public ChatDto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sayerId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sayerNickname_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_chat_ChatDto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_chat_ChatDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto.class, com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatDto> PARSER =
        new com.google.protobuf.AbstractParser<ChatDto>() {
      public ChatDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatDto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChatDto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 sayerId = 1;
    public static final int SAYERID_FIELD_NUMBER = 1;
    private long sayerId_;
    /**
     * <code>optional int64 sayerId = 1;</code>
     *
     * <pre>
     **
     * 发言者id
     * </pre>
     */
    public boolean hasSayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 sayerId = 1;</code>
     *
     * <pre>
     **
     * 发言者id
     * </pre>
     */
    public long getSayerId() {
      return sayerId_;
    }

    // optional string sayerNickname = 2;
    public static final int SAYERNICKNAME_FIELD_NUMBER = 2;
    private java.lang.Object sayerNickname_;
    /**
     * <code>optional string sayerNickname = 2;</code>
     *
     * <pre>
     **
     * 发言者昵称
     * </pre>
     */
    public boolean hasSayerNickname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string sayerNickname = 2;</code>
     *
     * <pre>
     **
     * 发言者昵称
     * </pre>
     */
    public java.lang.String getSayerNickname() {
      java.lang.Object ref = sayerNickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sayerNickname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sayerNickname = 2;</code>
     *
     * <pre>
     **
     * 发言者昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSayerNicknameBytes() {
      java.lang.Object ref = sayerNickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sayerNickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string content = 3;
    public static final int CONTENT_FIELD_NUMBER = 3;
    private java.lang.Object content_;
    /**
     * <code>optional string content = 3;</code>
     *
     * <pre>
     **
     * 发言内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string content = 3;</code>
     *
     * <pre>
     **
     * 发言内容
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 3;</code>
     *
     * <pre>
     **
     * 发言内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sayerId_ = 0L;
      sayerNickname_ = "";
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, sayerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSayerNicknameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sayerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSayerNicknameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.shadowgame.rpg.modules.protocol.dto.chat.ChatDto}
     *
     * <pre>
     **
     * 聊天dto
     * @author wcj10051891@gmail.com
     *字段列表:
     * //发言者id
     *java.lang.Long sayerId
     * //发言者昵称
     *java.lang.String sayerNickname
     * //发言内容
     *java.lang.String content
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_chat_ChatDto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_chat_ChatDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto.class, com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto.Builder.class);
      }

      // Construct using com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sayerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        sayerNickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_chat_ChatDto_descriptor;
      }

      public com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto getDefaultInstanceForType() {
        return com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto.getDefaultInstance();
      }

      public com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto build() {
        com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto buildPartial() {
        com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto result = new com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sayerId_ = sayerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sayerNickname_ = sayerNickname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto) {
          return mergeFrom((com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto other) {
        if (other == com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto.getDefaultInstance()) return this;
        if (other.hasSayerId()) {
          setSayerId(other.getSayerId());
        }
        if (other.hasSayerNickname()) {
          bitField0_ |= 0x00000002;
          sayerNickname_ = other.sayerNickname_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000004;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shadowgame.rpg.modules.protobuf.dto.chat.ChatDtoPROTO.ChatDto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 sayerId = 1;
      private long sayerId_ ;
      /**
       * <code>optional int64 sayerId = 1;</code>
       *
       * <pre>
       **
       * 发言者id
       * </pre>
       */
      public boolean hasSayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 sayerId = 1;</code>
       *
       * <pre>
       **
       * 发言者id
       * </pre>
       */
      public long getSayerId() {
        return sayerId_;
      }
      /**
       * <code>optional int64 sayerId = 1;</code>
       *
       * <pre>
       **
       * 发言者id
       * </pre>
       */
      public Builder setSayerId(long value) {
        bitField0_ |= 0x00000001;
        sayerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sayerId = 1;</code>
       *
       * <pre>
       **
       * 发言者id
       * </pre>
       */
      public Builder clearSayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sayerId_ = 0L;
        onChanged();
        return this;
      }

      // optional string sayerNickname = 2;
      private java.lang.Object sayerNickname_ = "";
      /**
       * <code>optional string sayerNickname = 2;</code>
       *
       * <pre>
       **
       * 发言者昵称
       * </pre>
       */
      public boolean hasSayerNickname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string sayerNickname = 2;</code>
       *
       * <pre>
       **
       * 发言者昵称
       * </pre>
       */
      public java.lang.String getSayerNickname() {
        java.lang.Object ref = sayerNickname_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sayerNickname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sayerNickname = 2;</code>
       *
       * <pre>
       **
       * 发言者昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSayerNicknameBytes() {
        java.lang.Object ref = sayerNickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sayerNickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sayerNickname = 2;</code>
       *
       * <pre>
       **
       * 发言者昵称
       * </pre>
       */
      public Builder setSayerNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sayerNickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sayerNickname = 2;</code>
       *
       * <pre>
       **
       * 发言者昵称
       * </pre>
       */
      public Builder clearSayerNickname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sayerNickname_ = getDefaultInstance().getSayerNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sayerNickname = 2;</code>
       *
       * <pre>
       **
       * 发言者昵称
       * </pre>
       */
      public Builder setSayerNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sayerNickname_ = value;
        onChanged();
        return this;
      }

      // optional string content = 3;
      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 3;</code>
       *
       * <pre>
       **
       * 发言内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string content = 3;</code>
       *
       * <pre>
       **
       * 发言内容
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 3;</code>
       *
       * <pre>
       **
       * 发言内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 3;</code>
       *
       * <pre>
       **
       * 发言内容
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 3;</code>
       *
       * <pre>
       **
       * 发言内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 3;</code>
       *
       * <pre>
       **
       * 发言内容
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.shadowgame.rpg.modules.protocol.dto.chat.ChatDto)
    }

    static {
      defaultInstance = new ChatDto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.shadowgame.rpg.modules.protocol.dto.chat.ChatDto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadowgame_rpg_modules_protocol_dto_chat_ChatDto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_shadowgame_rpg_modules_protocol_dto_chat_ChatDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n@com/shadowgame/rpg/modules/protocol/dt" +
      "o/chat/ChatDto_PROTO.proto\022,com.shadowga" +
      "me.rpg.modules.protocol.dto.chat\"B\n\007Chat" +
      "Dto\022\017\n\007sayerId\030\001 \001(\003\022\025\n\rsayerNickname\030\002 " +
      "\001(\t\022\017\n\007content\030\003 \001(\tB.\n,com.shadowgame.r" +
      "pg.modules.protobuf.dto.chat"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_shadowgame_rpg_modules_protocol_dto_chat_ChatDto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_shadowgame_rpg_modules_protocol_dto_chat_ChatDto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_shadowgame_rpg_modules_protocol_dto_chat_ChatDto_descriptor,
              new java.lang.String[] { "SayerId", "SayerNickname", "Content", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
