// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/shadowgame/rpg/modules/protocol/dto/battle/BattleReportDto_PROTO.proto

package com.shadowgame.rpg.modules.protobuf.dto.battle;

public final class BattleReportDtoPROTO {
  private BattleReportDtoPROTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BattleReportDtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string targetName = 1;
    /**
     * <code>optional string targetName = 1;</code>
     *
     * <pre>
     **
     * 目标名称
     * </pre>
     */
    boolean hasTargetName();
    /**
     * <code>optional string targetName = 1;</code>
     *
     * <pre>
     **
     * 目标名称
     * </pre>
     */
    java.lang.String getTargetName();
    /**
     * <code>optional string targetName = 1;</code>
     *
     * <pre>
     **
     * 目标名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getTargetNameBytes();

    // optional int32 targetLv = 2;
    /**
     * <code>optional int32 targetLv = 2;</code>
     *
     * <pre>
     **
     * 目标等级
     * </pre>
     */
    boolean hasTargetLv();
    /**
     * <code>optional int32 targetLv = 2;</code>
     *
     * <pre>
     **
     * 目标等级
     * </pre>
     */
    int getTargetLv();

    // optional int32 targetHp = 3;
    /**
     * <code>optional int32 targetHp = 3;</code>
     *
     * <pre>
     **
     * 目标血量
     * </pre>
     */
    boolean hasTargetHp();
    /**
     * <code>optional int32 targetHp = 3;</code>
     *
     * <pre>
     **
     * 目标血量
     * </pre>
     */
    int getTargetHp();

    // repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
     *
     * <pre>
     **
     * 目标出战家将列表
     * </pre>
     */
    java.util.List<com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto> 
        getTargetGeneralsList();
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
     *
     * <pre>
     **
     * 目标出战家将列表
     * </pre>
     */
    com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto getTargetGenerals(int index);
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
     *
     * <pre>
     **
     * 目标出战家将列表
     * </pre>
     */
    int getTargetGeneralsCount();
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
     *
     * <pre>
     **
     * 目标出战家将列表
     * </pre>
     */
    java.util.List<? extends com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDtoOrBuilder> 
        getTargetGeneralsOrBuilderList();
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
     *
     * <pre>
     **
     * 目标出战家将列表
     * </pre>
     */
    com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDtoOrBuilder getTargetGeneralsOrBuilder(
        int index);

    // repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
     *
     * <pre>
     **
     * 战斗回合过程
     * </pre>
     */
    java.util.List<com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto> 
        getRoundsList();
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
     *
     * <pre>
     **
     * 战斗回合过程
     * </pre>
     */
    com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto getRounds(int index);
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
     *
     * <pre>
     **
     * 战斗回合过程
     * </pre>
     */
    int getRoundsCount();
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
     *
     * <pre>
     **
     * 战斗回合过程
     * </pre>
     */
    java.util.List<? extends com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDtoOrBuilder> 
        getRoundsOrBuilderList();
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
     *
     * <pre>
     **
     * 战斗回合过程
     * </pre>
     */
    com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDtoOrBuilder getRoundsOrBuilder(
        int index);

    // optional bool win = 6;
    /**
     * <code>optional bool win = 6;</code>
     *
     * <pre>
     **
     * 是否胜利
     * </pre>
     */
    boolean hasWin();
    /**
     * <code>optional bool win = 6;</code>
     *
     * <pre>
     **
     * 是否胜利
     * </pre>
     */
    boolean getWin();

    // optional int32 star = 7;
    /**
     * <code>optional int32 star = 7;</code>
     *
     * <pre>
     **
     * 星级
     * </pre>
     */
    boolean hasStar();
    /**
     * <code>optional int32 star = 7;</code>
     *
     * <pre>
     **
     * 星级
     * </pre>
     */
    int getStar();

    // optional int32 loseHp = 8;
    /**
     * <code>optional int32 loseHp = 8;</code>
     *
     * <pre>
     **
     * 我方损失兵力
     * </pre>
     */
    boolean hasLoseHp();
    /**
     * <code>optional int32 loseHp = 8;</code>
     *
     * <pre>
     **
     * 我方损失兵力
     * </pre>
     */
    int getLoseHp();

    // optional int32 exploit = 9;
    /**
     * <code>optional int32 exploit = 9;</code>
     *
     * <pre>
     **
     * 获得军功
     * </pre>
     */
    boolean hasExploit();
    /**
     * <code>optional int32 exploit = 9;</code>
     *
     * <pre>
     **
     * 获得军功
     * </pre>
     */
    int getExploit();

    // optional string itemName = 10;
    /**
     * <code>optional string itemName = 10;</code>
     *
     * <pre>
     **
     * 获得装备
     * </pre>
     */
    boolean hasItemName();
    /**
     * <code>optional string itemName = 10;</code>
     *
     * <pre>
     **
     * 获得装备
     * </pre>
     */
    java.lang.String getItemName();
    /**
     * <code>optional string itemName = 10;</code>
     *
     * <pre>
     **
     * 获得装备
     * </pre>
     */
    com.google.protobuf.ByteString
        getItemNameBytes();
  }
  /**
   * Protobuf type {@code com.shadowgame.rpg.modules.protocol.dto.battle.BattleReportDto}
   *
   * <pre>
   **
   * 战报dto
   * @author wcj10051891@gmail.com
   *字段列表:
   * //目标名称
   *java.lang.String targetName
   * //目标等级
   *int targetLv
   * //目标血量
   *int targetHp
   * //目标出战家将列表
   *java.util.List&lt;com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto&gt; targetGenerals
   * //战斗回合过程
   *java.util.List&lt;com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto&gt; rounds
   * //是否胜利
   *boolean win
   * //星级
   *int star
   * //我方损失兵力
   *int loseHp
   * //获得军功
   *int exploit
   * //获得装备
   *java.lang.String itemName
   * </pre>
   */
  public static final class BattleReportDto extends
      com.google.protobuf.GeneratedMessage
      implements BattleReportDtoOrBuilder {
    // Use BattleReportDto.newBuilder() to construct.
    private BattleReportDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BattleReportDto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BattleReportDto defaultInstance;
    public static BattleReportDto getDefaultInstance() {
      return defaultInstance;
    }

    public BattleReportDto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BattleReportDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              targetName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              targetLv_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              targetHp_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                targetGenerals_ = new java.util.ArrayList<com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto>();
                mutable_bitField0_ |= 0x00000008;
              }
              targetGenerals_.add(input.readMessage(com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.PARSER, extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                rounds_ = new java.util.ArrayList<com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto>();
                mutable_bitField0_ |= 0x00000010;
              }
              rounds_.add(input.readMessage(com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.PARSER, extensionRegistry));
              break;
            }
            case 48: {
              bitField0_ |= 0x00000008;
              win_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000010;
              star_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000020;
              loseHp_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000040;
              exploit_ = input.readInt32();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000080;
              itemName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          targetGenerals_ = java.util.Collections.unmodifiableList(targetGenerals_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          rounds_ = java.util.Collections.unmodifiableList(rounds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_battle_BattleReportDto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_battle_BattleReportDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto.class, com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto.Builder.class);
    }

    public static com.google.protobuf.Parser<BattleReportDto> PARSER =
        new com.google.protobuf.AbstractParser<BattleReportDto>() {
      public BattleReportDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BattleReportDto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BattleReportDto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string targetName = 1;
    public static final int TARGETNAME_FIELD_NUMBER = 1;
    private java.lang.Object targetName_;
    /**
     * <code>optional string targetName = 1;</code>
     *
     * <pre>
     **
     * 目标名称
     * </pre>
     */
    public boolean hasTargetName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string targetName = 1;</code>
     *
     * <pre>
     **
     * 目标名称
     * </pre>
     */
    public java.lang.String getTargetName() {
      java.lang.Object ref = targetName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string targetName = 1;</code>
     *
     * <pre>
     **
     * 目标名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTargetNameBytes() {
      java.lang.Object ref = targetName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 targetLv = 2;
    public static final int TARGETLV_FIELD_NUMBER = 2;
    private int targetLv_;
    /**
     * <code>optional int32 targetLv = 2;</code>
     *
     * <pre>
     **
     * 目标等级
     * </pre>
     */
    public boolean hasTargetLv() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 targetLv = 2;</code>
     *
     * <pre>
     **
     * 目标等级
     * </pre>
     */
    public int getTargetLv() {
      return targetLv_;
    }

    // optional int32 targetHp = 3;
    public static final int TARGETHP_FIELD_NUMBER = 3;
    private int targetHp_;
    /**
     * <code>optional int32 targetHp = 3;</code>
     *
     * <pre>
     **
     * 目标血量
     * </pre>
     */
    public boolean hasTargetHp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 targetHp = 3;</code>
     *
     * <pre>
     **
     * 目标血量
     * </pre>
     */
    public int getTargetHp() {
      return targetHp_;
    }

    // repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;
    public static final int TARGETGENERALS_FIELD_NUMBER = 4;
    private java.util.List<com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto> targetGenerals_;
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
     *
     * <pre>
     **
     * 目标出战家将列表
     * </pre>
     */
    public java.util.List<com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto> getTargetGeneralsList() {
      return targetGenerals_;
    }
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
     *
     * <pre>
     **
     * 目标出战家将列表
     * </pre>
     */
    public java.util.List<? extends com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDtoOrBuilder> 
        getTargetGeneralsOrBuilderList() {
      return targetGenerals_;
    }
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
     *
     * <pre>
     **
     * 目标出战家将列表
     * </pre>
     */
    public int getTargetGeneralsCount() {
      return targetGenerals_.size();
    }
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
     *
     * <pre>
     **
     * 目标出战家将列表
     * </pre>
     */
    public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto getTargetGenerals(int index) {
      return targetGenerals_.get(index);
    }
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
     *
     * <pre>
     **
     * 目标出战家将列表
     * </pre>
     */
    public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDtoOrBuilder getTargetGeneralsOrBuilder(
        int index) {
      return targetGenerals_.get(index);
    }

    // repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;
    public static final int ROUNDS_FIELD_NUMBER = 5;
    private java.util.List<com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto> rounds_;
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
     *
     * <pre>
     **
     * 战斗回合过程
     * </pre>
     */
    public java.util.List<com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto> getRoundsList() {
      return rounds_;
    }
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
     *
     * <pre>
     **
     * 战斗回合过程
     * </pre>
     */
    public java.util.List<? extends com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDtoOrBuilder> 
        getRoundsOrBuilderList() {
      return rounds_;
    }
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
     *
     * <pre>
     **
     * 战斗回合过程
     * </pre>
     */
    public int getRoundsCount() {
      return rounds_.size();
    }
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
     *
     * <pre>
     **
     * 战斗回合过程
     * </pre>
     */
    public com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto getRounds(int index) {
      return rounds_.get(index);
    }
    /**
     * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
     *
     * <pre>
     **
     * 战斗回合过程
     * </pre>
     */
    public com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDtoOrBuilder getRoundsOrBuilder(
        int index) {
      return rounds_.get(index);
    }

    // optional bool win = 6;
    public static final int WIN_FIELD_NUMBER = 6;
    private boolean win_;
    /**
     * <code>optional bool win = 6;</code>
     *
     * <pre>
     **
     * 是否胜利
     * </pre>
     */
    public boolean hasWin() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool win = 6;</code>
     *
     * <pre>
     **
     * 是否胜利
     * </pre>
     */
    public boolean getWin() {
      return win_;
    }

    // optional int32 star = 7;
    public static final int STAR_FIELD_NUMBER = 7;
    private int star_;
    /**
     * <code>optional int32 star = 7;</code>
     *
     * <pre>
     **
     * 星级
     * </pre>
     */
    public boolean hasStar() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 star = 7;</code>
     *
     * <pre>
     **
     * 星级
     * </pre>
     */
    public int getStar() {
      return star_;
    }

    // optional int32 loseHp = 8;
    public static final int LOSEHP_FIELD_NUMBER = 8;
    private int loseHp_;
    /**
     * <code>optional int32 loseHp = 8;</code>
     *
     * <pre>
     **
     * 我方损失兵力
     * </pre>
     */
    public boolean hasLoseHp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 loseHp = 8;</code>
     *
     * <pre>
     **
     * 我方损失兵力
     * </pre>
     */
    public int getLoseHp() {
      return loseHp_;
    }

    // optional int32 exploit = 9;
    public static final int EXPLOIT_FIELD_NUMBER = 9;
    private int exploit_;
    /**
     * <code>optional int32 exploit = 9;</code>
     *
     * <pre>
     **
     * 获得军功
     * </pre>
     */
    public boolean hasExploit() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 exploit = 9;</code>
     *
     * <pre>
     **
     * 获得军功
     * </pre>
     */
    public int getExploit() {
      return exploit_;
    }

    // optional string itemName = 10;
    public static final int ITEMNAME_FIELD_NUMBER = 10;
    private java.lang.Object itemName_;
    /**
     * <code>optional string itemName = 10;</code>
     *
     * <pre>
     **
     * 获得装备
     * </pre>
     */
    public boolean hasItemName() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string itemName = 10;</code>
     *
     * <pre>
     **
     * 获得装备
     * </pre>
     */
    public java.lang.String getItemName() {
      java.lang.Object ref = itemName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          itemName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string itemName = 10;</code>
     *
     * <pre>
     **
     * 获得装备
     * </pre>
     */
    public com.google.protobuf.ByteString
        getItemNameBytes() {
      java.lang.Object ref = itemName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      targetName_ = "";
      targetLv_ = 0;
      targetHp_ = 0;
      targetGenerals_ = java.util.Collections.emptyList();
      rounds_ = java.util.Collections.emptyList();
      win_ = false;
      star_ = 0;
      loseHp_ = 0;
      exploit_ = 0;
      itemName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTargetNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, targetLv_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, targetHp_);
      }
      for (int i = 0; i < targetGenerals_.size(); i++) {
        output.writeMessage(4, targetGenerals_.get(i));
      }
      for (int i = 0; i < rounds_.size(); i++) {
        output.writeMessage(5, rounds_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(6, win_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(7, star_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(8, loseHp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(9, exploit_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(10, getItemNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTargetNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, targetLv_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, targetHp_);
      }
      for (int i = 0; i < targetGenerals_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, targetGenerals_.get(i));
      }
      for (int i = 0; i < rounds_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, rounds_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, win_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, star_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, loseHp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, exploit_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getItemNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.shadowgame.rpg.modules.protocol.dto.battle.BattleReportDto}
     *
     * <pre>
     **
     * 战报dto
     * @author wcj10051891@gmail.com
     *字段列表:
     * //目标名称
     *java.lang.String targetName
     * //目标等级
     *int targetLv
     * //目标血量
     *int targetHp
     * //目标出战家将列表
     *java.util.List&lt;com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto&gt; targetGenerals
     * //战斗回合过程
     *java.util.List&lt;com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto&gt; rounds
     * //是否胜利
     *boolean win
     * //星级
     *int star
     * //我方损失兵力
     *int loseHp
     * //获得军功
     *int exploit
     * //获得装备
     *java.lang.String itemName
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_battle_BattleReportDto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_battle_BattleReportDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto.class, com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto.Builder.class);
      }

      // Construct using com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTargetGeneralsFieldBuilder();
          getRoundsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        targetName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        targetLv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        targetHp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (targetGeneralsBuilder_ == null) {
          targetGenerals_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          targetGeneralsBuilder_.clear();
        }
        if (roundsBuilder_ == null) {
          rounds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          roundsBuilder_.clear();
        }
        win_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        star_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        loseHp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        exploit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        itemName_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_battle_BattleReportDto_descriptor;
      }

      public com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto getDefaultInstanceForType() {
        return com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto.getDefaultInstance();
      }

      public com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto build() {
        com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto buildPartial() {
        com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto result = new com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.targetName_ = targetName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.targetLv_ = targetLv_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.targetHp_ = targetHp_;
        if (targetGeneralsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            targetGenerals_ = java.util.Collections.unmodifiableList(targetGenerals_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.targetGenerals_ = targetGenerals_;
        } else {
          result.targetGenerals_ = targetGeneralsBuilder_.build();
        }
        if (roundsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            rounds_ = java.util.Collections.unmodifiableList(rounds_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.rounds_ = rounds_;
        } else {
          result.rounds_ = roundsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        result.win_ = win_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000010;
        }
        result.star_ = star_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000020;
        }
        result.loseHp_ = loseHp_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000040;
        }
        result.exploit_ = exploit_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000080;
        }
        result.itemName_ = itemName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto) {
          return mergeFrom((com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto other) {
        if (other == com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto.getDefaultInstance()) return this;
        if (other.hasTargetName()) {
          bitField0_ |= 0x00000001;
          targetName_ = other.targetName_;
          onChanged();
        }
        if (other.hasTargetLv()) {
          setTargetLv(other.getTargetLv());
        }
        if (other.hasTargetHp()) {
          setTargetHp(other.getTargetHp());
        }
        if (targetGeneralsBuilder_ == null) {
          if (!other.targetGenerals_.isEmpty()) {
            if (targetGenerals_.isEmpty()) {
              targetGenerals_ = other.targetGenerals_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureTargetGeneralsIsMutable();
              targetGenerals_.addAll(other.targetGenerals_);
            }
            onChanged();
          }
        } else {
          if (!other.targetGenerals_.isEmpty()) {
            if (targetGeneralsBuilder_.isEmpty()) {
              targetGeneralsBuilder_.dispose();
              targetGeneralsBuilder_ = null;
              targetGenerals_ = other.targetGenerals_;
              bitField0_ = (bitField0_ & ~0x00000008);
              targetGeneralsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTargetGeneralsFieldBuilder() : null;
            } else {
              targetGeneralsBuilder_.addAllMessages(other.targetGenerals_);
            }
          }
        }
        if (roundsBuilder_ == null) {
          if (!other.rounds_.isEmpty()) {
            if (rounds_.isEmpty()) {
              rounds_ = other.rounds_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureRoundsIsMutable();
              rounds_.addAll(other.rounds_);
            }
            onChanged();
          }
        } else {
          if (!other.rounds_.isEmpty()) {
            if (roundsBuilder_.isEmpty()) {
              roundsBuilder_.dispose();
              roundsBuilder_ = null;
              rounds_ = other.rounds_;
              bitField0_ = (bitField0_ & ~0x00000010);
              roundsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRoundsFieldBuilder() : null;
            } else {
              roundsBuilder_.addAllMessages(other.rounds_);
            }
          }
        }
        if (other.hasWin()) {
          setWin(other.getWin());
        }
        if (other.hasStar()) {
          setStar(other.getStar());
        }
        if (other.hasLoseHp()) {
          setLoseHp(other.getLoseHp());
        }
        if (other.hasExploit()) {
          setExploit(other.getExploit());
        }
        if (other.hasItemName()) {
          bitField0_ |= 0x00000200;
          itemName_ = other.itemName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shadowgame.rpg.modules.protobuf.dto.battle.BattleReportDtoPROTO.BattleReportDto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string targetName = 1;
      private java.lang.Object targetName_ = "";
      /**
       * <code>optional string targetName = 1;</code>
       *
       * <pre>
       **
       * 目标名称
       * </pre>
       */
      public boolean hasTargetName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string targetName = 1;</code>
       *
       * <pre>
       **
       * 目标名称
       * </pre>
       */
      public java.lang.String getTargetName() {
        java.lang.Object ref = targetName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          targetName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string targetName = 1;</code>
       *
       * <pre>
       **
       * 目标名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTargetNameBytes() {
        java.lang.Object ref = targetName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string targetName = 1;</code>
       *
       * <pre>
       **
       * 目标名称
       * </pre>
       */
      public Builder setTargetName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        targetName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetName = 1;</code>
       *
       * <pre>
       **
       * 目标名称
       * </pre>
       */
      public Builder clearTargetName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        targetName_ = getDefaultInstance().getTargetName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetName = 1;</code>
       *
       * <pre>
       **
       * 目标名称
       * </pre>
       */
      public Builder setTargetNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        targetName_ = value;
        onChanged();
        return this;
      }

      // optional int32 targetLv = 2;
      private int targetLv_ ;
      /**
       * <code>optional int32 targetLv = 2;</code>
       *
       * <pre>
       **
       * 目标等级
       * </pre>
       */
      public boolean hasTargetLv() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 targetLv = 2;</code>
       *
       * <pre>
       **
       * 目标等级
       * </pre>
       */
      public int getTargetLv() {
        return targetLv_;
      }
      /**
       * <code>optional int32 targetLv = 2;</code>
       *
       * <pre>
       **
       * 目标等级
       * </pre>
       */
      public Builder setTargetLv(int value) {
        bitField0_ |= 0x00000002;
        targetLv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 targetLv = 2;</code>
       *
       * <pre>
       **
       * 目标等级
       * </pre>
       */
      public Builder clearTargetLv() {
        bitField0_ = (bitField0_ & ~0x00000002);
        targetLv_ = 0;
        onChanged();
        return this;
      }

      // optional int32 targetHp = 3;
      private int targetHp_ ;
      /**
       * <code>optional int32 targetHp = 3;</code>
       *
       * <pre>
       **
       * 目标血量
       * </pre>
       */
      public boolean hasTargetHp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 targetHp = 3;</code>
       *
       * <pre>
       **
       * 目标血量
       * </pre>
       */
      public int getTargetHp() {
        return targetHp_;
      }
      /**
       * <code>optional int32 targetHp = 3;</code>
       *
       * <pre>
       **
       * 目标血量
       * </pre>
       */
      public Builder setTargetHp(int value) {
        bitField0_ |= 0x00000004;
        targetHp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 targetHp = 3;</code>
       *
       * <pre>
       **
       * 目标血量
       * </pre>
       */
      public Builder clearTargetHp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        targetHp_ = 0;
        onChanged();
        return this;
      }

      // repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;
      private java.util.List<com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto> targetGenerals_ =
        java.util.Collections.emptyList();
      private void ensureTargetGeneralsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          targetGenerals_ = new java.util.ArrayList<com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto>(targetGenerals_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.Builder, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDtoOrBuilder> targetGeneralsBuilder_;

      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public java.util.List<com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto> getTargetGeneralsList() {
        if (targetGeneralsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(targetGenerals_);
        } else {
          return targetGeneralsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public int getTargetGeneralsCount() {
        if (targetGeneralsBuilder_ == null) {
          return targetGenerals_.size();
        } else {
          return targetGeneralsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto getTargetGenerals(int index) {
        if (targetGeneralsBuilder_ == null) {
          return targetGenerals_.get(index);
        } else {
          return targetGeneralsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public Builder setTargetGenerals(
          int index, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto value) {
        if (targetGeneralsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTargetGeneralsIsMutable();
          targetGenerals_.set(index, value);
          onChanged();
        } else {
          targetGeneralsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public Builder setTargetGenerals(
          int index, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.Builder builderForValue) {
        if (targetGeneralsBuilder_ == null) {
          ensureTargetGeneralsIsMutable();
          targetGenerals_.set(index, builderForValue.build());
          onChanged();
        } else {
          targetGeneralsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public Builder addTargetGenerals(com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto value) {
        if (targetGeneralsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTargetGeneralsIsMutable();
          targetGenerals_.add(value);
          onChanged();
        } else {
          targetGeneralsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public Builder addTargetGenerals(
          int index, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto value) {
        if (targetGeneralsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTargetGeneralsIsMutable();
          targetGenerals_.add(index, value);
          onChanged();
        } else {
          targetGeneralsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public Builder addTargetGenerals(
          com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.Builder builderForValue) {
        if (targetGeneralsBuilder_ == null) {
          ensureTargetGeneralsIsMutable();
          targetGenerals_.add(builderForValue.build());
          onChanged();
        } else {
          targetGeneralsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public Builder addTargetGenerals(
          int index, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.Builder builderForValue) {
        if (targetGeneralsBuilder_ == null) {
          ensureTargetGeneralsIsMutable();
          targetGenerals_.add(index, builderForValue.build());
          onChanged();
        } else {
          targetGeneralsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public Builder addAllTargetGenerals(
          java.lang.Iterable<? extends com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto> values) {
        if (targetGeneralsBuilder_ == null) {
          ensureTargetGeneralsIsMutable();
          super.addAll(values, targetGenerals_);
          onChanged();
        } else {
          targetGeneralsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public Builder clearTargetGenerals() {
        if (targetGeneralsBuilder_ == null) {
          targetGenerals_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          targetGeneralsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public Builder removeTargetGenerals(int index) {
        if (targetGeneralsBuilder_ == null) {
          ensureTargetGeneralsIsMutable();
          targetGenerals_.remove(index);
          onChanged();
        } else {
          targetGeneralsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.Builder getTargetGeneralsBuilder(
          int index) {
        return getTargetGeneralsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDtoOrBuilder getTargetGeneralsOrBuilder(
          int index) {
        if (targetGeneralsBuilder_ == null) {
          return targetGenerals_.get(index);  } else {
          return targetGeneralsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public java.util.List<? extends com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDtoOrBuilder> 
           getTargetGeneralsOrBuilderList() {
        if (targetGeneralsBuilder_ != null) {
          return targetGeneralsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(targetGenerals_);
        }
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.Builder addTargetGeneralsBuilder() {
        return getTargetGeneralsFieldBuilder().addBuilder(
            com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.getDefaultInstance());
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.Builder addTargetGeneralsBuilder(
          int index) {
        return getTargetGeneralsFieldBuilder().addBuilder(
            index, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.getDefaultInstance());
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.generals.GeneralsDto targetGenerals = 4;</code>
       *
       * <pre>
       **
       * 目标出战家将列表
       * </pre>
       */
      public java.util.List<com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.Builder> 
           getTargetGeneralsBuilderList() {
        return getTargetGeneralsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.Builder, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDtoOrBuilder> 
          getTargetGeneralsFieldBuilder() {
        if (targetGeneralsBuilder_ == null) {
          targetGeneralsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDto.Builder, com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.GeneralsDtoOrBuilder>(
                  targetGenerals_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          targetGenerals_ = null;
        }
        return targetGeneralsBuilder_;
      }

      // repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;
      private java.util.List<com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto> rounds_ =
        java.util.Collections.emptyList();
      private void ensureRoundsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          rounds_ = new java.util.ArrayList<com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto>(rounds_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto, com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.Builder, com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDtoOrBuilder> roundsBuilder_;

      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public java.util.List<com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto> getRoundsList() {
        if (roundsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rounds_);
        } else {
          return roundsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public int getRoundsCount() {
        if (roundsBuilder_ == null) {
          return rounds_.size();
        } else {
          return roundsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto getRounds(int index) {
        if (roundsBuilder_ == null) {
          return rounds_.get(index);
        } else {
          return roundsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public Builder setRounds(
          int index, com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto value) {
        if (roundsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoundsIsMutable();
          rounds_.set(index, value);
          onChanged();
        } else {
          roundsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public Builder setRounds(
          int index, com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.Builder builderForValue) {
        if (roundsBuilder_ == null) {
          ensureRoundsIsMutable();
          rounds_.set(index, builderForValue.build());
          onChanged();
        } else {
          roundsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public Builder addRounds(com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto value) {
        if (roundsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoundsIsMutable();
          rounds_.add(value);
          onChanged();
        } else {
          roundsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public Builder addRounds(
          int index, com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto value) {
        if (roundsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoundsIsMutable();
          rounds_.add(index, value);
          onChanged();
        } else {
          roundsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public Builder addRounds(
          com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.Builder builderForValue) {
        if (roundsBuilder_ == null) {
          ensureRoundsIsMutable();
          rounds_.add(builderForValue.build());
          onChanged();
        } else {
          roundsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public Builder addRounds(
          int index, com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.Builder builderForValue) {
        if (roundsBuilder_ == null) {
          ensureRoundsIsMutable();
          rounds_.add(index, builderForValue.build());
          onChanged();
        } else {
          roundsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public Builder addAllRounds(
          java.lang.Iterable<? extends com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto> values) {
        if (roundsBuilder_ == null) {
          ensureRoundsIsMutable();
          super.addAll(values, rounds_);
          onChanged();
        } else {
          roundsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public Builder clearRounds() {
        if (roundsBuilder_ == null) {
          rounds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          roundsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public Builder removeRounds(int index) {
        if (roundsBuilder_ == null) {
          ensureRoundsIsMutable();
          rounds_.remove(index);
          onChanged();
        } else {
          roundsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.Builder getRoundsBuilder(
          int index) {
        return getRoundsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDtoOrBuilder getRoundsOrBuilder(
          int index) {
        if (roundsBuilder_ == null) {
          return rounds_.get(index);  } else {
          return roundsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public java.util.List<? extends com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDtoOrBuilder> 
           getRoundsOrBuilderList() {
        if (roundsBuilder_ != null) {
          return roundsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rounds_);
        }
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.Builder addRoundsBuilder() {
        return getRoundsFieldBuilder().addBuilder(
            com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.getDefaultInstance());
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.Builder addRoundsBuilder(
          int index) {
        return getRoundsFieldBuilder().addBuilder(
            index, com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.getDefaultInstance());
      }
      /**
       * <code>repeated .com.shadowgame.rpg.modules.protocol.dto.battle.FightRoundDto rounds = 5;</code>
       *
       * <pre>
       **
       * 战斗回合过程
       * </pre>
       */
      public java.util.List<com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.Builder> 
           getRoundsBuilderList() {
        return getRoundsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto, com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.Builder, com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDtoOrBuilder> 
          getRoundsFieldBuilder() {
        if (roundsBuilder_ == null) {
          roundsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto, com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDto.Builder, com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.FightRoundDtoOrBuilder>(
                  rounds_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          rounds_ = null;
        }
        return roundsBuilder_;
      }

      // optional bool win = 6;
      private boolean win_ ;
      /**
       * <code>optional bool win = 6;</code>
       *
       * <pre>
       **
       * 是否胜利
       * </pre>
       */
      public boolean hasWin() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool win = 6;</code>
       *
       * <pre>
       **
       * 是否胜利
       * </pre>
       */
      public boolean getWin() {
        return win_;
      }
      /**
       * <code>optional bool win = 6;</code>
       *
       * <pre>
       **
       * 是否胜利
       * </pre>
       */
      public Builder setWin(boolean value) {
        bitField0_ |= 0x00000020;
        win_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool win = 6;</code>
       *
       * <pre>
       **
       * 是否胜利
       * </pre>
       */
      public Builder clearWin() {
        bitField0_ = (bitField0_ & ~0x00000020);
        win_ = false;
        onChanged();
        return this;
      }

      // optional int32 star = 7;
      private int star_ ;
      /**
       * <code>optional int32 star = 7;</code>
       *
       * <pre>
       **
       * 星级
       * </pre>
       */
      public boolean hasStar() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 star = 7;</code>
       *
       * <pre>
       **
       * 星级
       * </pre>
       */
      public int getStar() {
        return star_;
      }
      /**
       * <code>optional int32 star = 7;</code>
       *
       * <pre>
       **
       * 星级
       * </pre>
       */
      public Builder setStar(int value) {
        bitField0_ |= 0x00000040;
        star_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 star = 7;</code>
       *
       * <pre>
       **
       * 星级
       * </pre>
       */
      public Builder clearStar() {
        bitField0_ = (bitField0_ & ~0x00000040);
        star_ = 0;
        onChanged();
        return this;
      }

      // optional int32 loseHp = 8;
      private int loseHp_ ;
      /**
       * <code>optional int32 loseHp = 8;</code>
       *
       * <pre>
       **
       * 我方损失兵力
       * </pre>
       */
      public boolean hasLoseHp() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 loseHp = 8;</code>
       *
       * <pre>
       **
       * 我方损失兵力
       * </pre>
       */
      public int getLoseHp() {
        return loseHp_;
      }
      /**
       * <code>optional int32 loseHp = 8;</code>
       *
       * <pre>
       **
       * 我方损失兵力
       * </pre>
       */
      public Builder setLoseHp(int value) {
        bitField0_ |= 0x00000080;
        loseHp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 loseHp = 8;</code>
       *
       * <pre>
       **
       * 我方损失兵力
       * </pre>
       */
      public Builder clearLoseHp() {
        bitField0_ = (bitField0_ & ~0x00000080);
        loseHp_ = 0;
        onChanged();
        return this;
      }

      // optional int32 exploit = 9;
      private int exploit_ ;
      /**
       * <code>optional int32 exploit = 9;</code>
       *
       * <pre>
       **
       * 获得军功
       * </pre>
       */
      public boolean hasExploit() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 exploit = 9;</code>
       *
       * <pre>
       **
       * 获得军功
       * </pre>
       */
      public int getExploit() {
        return exploit_;
      }
      /**
       * <code>optional int32 exploit = 9;</code>
       *
       * <pre>
       **
       * 获得军功
       * </pre>
       */
      public Builder setExploit(int value) {
        bitField0_ |= 0x00000100;
        exploit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 exploit = 9;</code>
       *
       * <pre>
       **
       * 获得军功
       * </pre>
       */
      public Builder clearExploit() {
        bitField0_ = (bitField0_ & ~0x00000100);
        exploit_ = 0;
        onChanged();
        return this;
      }

      // optional string itemName = 10;
      private java.lang.Object itemName_ = "";
      /**
       * <code>optional string itemName = 10;</code>
       *
       * <pre>
       **
       * 获得装备
       * </pre>
       */
      public boolean hasItemName() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string itemName = 10;</code>
       *
       * <pre>
       **
       * 获得装备
       * </pre>
       */
      public java.lang.String getItemName() {
        java.lang.Object ref = itemName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          itemName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string itemName = 10;</code>
       *
       * <pre>
       **
       * 获得装备
       * </pre>
       */
      public com.google.protobuf.ByteString
          getItemNameBytes() {
        java.lang.Object ref = itemName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string itemName = 10;</code>
       *
       * <pre>
       **
       * 获得装备
       * </pre>
       */
      public Builder setItemName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        itemName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string itemName = 10;</code>
       *
       * <pre>
       **
       * 获得装备
       * </pre>
       */
      public Builder clearItemName() {
        bitField0_ = (bitField0_ & ~0x00000200);
        itemName_ = getDefaultInstance().getItemName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string itemName = 10;</code>
       *
       * <pre>
       **
       * 获得装备
       * </pre>
       */
      public Builder setItemNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        itemName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.shadowgame.rpg.modules.protocol.dto.battle.BattleReportDto)
    }

    static {
      defaultInstance = new BattleReportDto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.shadowgame.rpg.modules.protocol.dto.battle.BattleReportDto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadowgame_rpg_modules_protocol_dto_battle_BattleReportDto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_shadowgame_rpg_modules_protocol_dto_battle_BattleReportDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nJcom/shadowgame/rpg/modules/protocol/dt" +
      "o/battle/BattleReportDto_PROTO.proto\022.co" +
      "m.shadowgame.rpg.modules.protocol.dto.ba" +
      "ttle\032Hcom/shadowgame/rpg/modules/protoco" +
      "l/dto/battle/FightRoundDto_PROTO.proto\032H" +
      "com/shadowgame/rpg/modules/protocol/dto/" +
      "generals/GeneralsDto_PROTO.proto\"\275\002\n\017Bat" +
      "tleReportDto\022\022\n\ntargetName\030\001 \001(\t\022\020\n\010targ" +
      "etLv\030\002 \001(\005\022\020\n\010targetHp\030\003 \001(\005\022U\n\016targetGe" +
      "nerals\030\004 \003(\0132=.com.shadowgame.rpg.module",
      "s.protocol.dto.generals.GeneralsDto\022M\n\006r" +
      "ounds\030\005 \003(\0132=.com.shadowgame.rpg.modules" +
      ".protocol.dto.battle.FightRoundDto\022\013\n\003wi" +
      "n\030\006 \001(\010\022\014\n\004star\030\007 \001(\005\022\016\n\006loseHp\030\010 \001(\005\022\017\n" +
      "\007exploit\030\t \001(\005\022\020\n\010itemName\030\n \001(\tB0\n.com." +
      "shadowgame.rpg.modules.protobuf.dto.batt" +
      "le"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_shadowgame_rpg_modules_protocol_dto_battle_BattleReportDto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_shadowgame_rpg_modules_protocol_dto_battle_BattleReportDto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_shadowgame_rpg_modules_protocol_dto_battle_BattleReportDto_descriptor,
              new java.lang.String[] { "TargetName", "TargetLv", "TargetHp", "TargetGenerals", "Rounds", "Win", "Star", "LoseHp", "Exploit", "ItemName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.shadowgame.rpg.modules.protobuf.dto.battle.FightRoundDtoPROTO.getDescriptor(),
          com.shadowgame.rpg.modules.protobuf.dto.generals.GeneralsDtoPROTO.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
