// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/shadowgame/rpg/modules/protocol/dto/player/LoginResultDto.proto

package com.shadowgame.rpg.modules.protocol.dto.player;

public final class LoginResultDto$$Gen {
  private LoginResultDto$$Gen() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginResultDtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool success = 1;
    /**
     * <code>optional bool success = 1;</code>
     */
    boolean hasSuccess();
    /**
     * <code>optional bool success = 1;</code>
     */
    boolean getSuccess();

    // optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
     */
    boolean hasPlayerDto();
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
     */
    com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto getPlayerDto();
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
     */
    com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDtoOrBuilder getPlayerDtoOrBuilder();
  }
  /**
   * Protobuf type {@code com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto}
   */
  public static final class LoginResultDto extends
      com.google.protobuf.GeneratedMessage
      implements LoginResultDtoOrBuilder {
    // Use LoginResultDto.newBuilder() to construct.
    private LoginResultDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginResultDto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginResultDto defaultInstance;
    public static LoginResultDto getDefaultInstance() {
      return defaultInstance;
    }

    public LoginResultDto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginResultDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              success_ = input.readBool();
              break;
            }
            case 18: {
              com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = playerDto_.toBuilder();
              }
              playerDto_ = input.readMessage(com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(playerDto_);
                playerDto_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.internal_static_com_shadowgame_rpg_modules_protocol_dto_player_LoginResultDto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.internal_static_com_shadowgame_rpg_modules_protocol_dto_player_LoginResultDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto.class, com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginResultDto> PARSER =
        new com.google.protobuf.AbstractParser<LoginResultDto>() {
      public LoginResultDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginResultDto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResultDto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool success = 1;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    // optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;
    public static final int PLAYERDTO_FIELD_NUMBER = 2;
    private com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto playerDto_;
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
     */
    public boolean hasPlayerDto() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
     */
    public com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto getPlayerDto() {
      return playerDto_;
    }
    /**
     * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
     */
    public com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDtoOrBuilder getPlayerDtoOrBuilder() {
      return playerDto_;
    }

    private void initFields() {
      success_ = false;
      playerDto_ = com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, success_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, playerDto_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, playerDto_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.internal_static_com_shadowgame_rpg_modules_protocol_dto_player_LoginResultDto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.internal_static_com_shadowgame_rpg_modules_protocol_dto_player_LoginResultDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto.class, com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto.Builder.class);
      }

      // Construct using com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayerDtoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (playerDtoBuilder_ == null) {
          playerDto_ = com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.getDefaultInstance();
        } else {
          playerDtoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.internal_static_com_shadowgame_rpg_modules_protocol_dto_player_LoginResultDto_descriptor;
      }

      public com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto getDefaultInstanceForType() {
        return com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto.getDefaultInstance();
      }

      public com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto build() {
        com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto buildPartial() {
        com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto result = new com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.success_ = success_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (playerDtoBuilder_ == null) {
          result.playerDto_ = playerDto_;
        } else {
          result.playerDto_ = playerDtoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto) {
          return mergeFrom((com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto other) {
        if (other == com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        if (other.hasPlayerDto()) {
          mergePlayerDto(other.getPlayerDto());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto$$Gen.LoginResultDto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool success = 1;
      private boolean success_ ;
      /**
       * <code>optional bool success = 1;</code>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      // optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;
      private com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto playerDto_ = com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto, com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.Builder, com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDtoOrBuilder> playerDtoBuilder_;
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
       */
      public boolean hasPlayerDto() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
       */
      public com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto getPlayerDto() {
        if (playerDtoBuilder_ == null) {
          return playerDto_;
        } else {
          return playerDtoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
       */
      public Builder setPlayerDto(com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto value) {
        if (playerDtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playerDto_ = value;
          onChanged();
        } else {
          playerDtoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
       */
      public Builder setPlayerDto(
          com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.Builder builderForValue) {
        if (playerDtoBuilder_ == null) {
          playerDto_ = builderForValue.build();
          onChanged();
        } else {
          playerDtoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
       */
      public Builder mergePlayerDto(com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto value) {
        if (playerDtoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              playerDto_ != com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.getDefaultInstance()) {
            playerDto_ =
              com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.newBuilder(playerDto_).mergeFrom(value).buildPartial();
          } else {
            playerDto_ = value;
          }
          onChanged();
        } else {
          playerDtoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
       */
      public Builder clearPlayerDto() {
        if (playerDtoBuilder_ == null) {
          playerDto_ = com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.getDefaultInstance();
          onChanged();
        } else {
          playerDtoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
       */
      public com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.Builder getPlayerDtoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPlayerDtoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
       */
      public com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDtoOrBuilder getPlayerDtoOrBuilder() {
        if (playerDtoBuilder_ != null) {
          return playerDtoBuilder_.getMessageOrBuilder();
        } else {
          return playerDto_;
        }
      }
      /**
       * <code>optional .com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto playerDto = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto, com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.Builder, com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDtoOrBuilder> 
          getPlayerDtoFieldBuilder() {
        if (playerDtoBuilder_ == null) {
          playerDtoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto, com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDto.Builder, com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.PlayerDtoOrBuilder>(
                  playerDto_,
                  getParentForChildren(),
                  isClean());
          playerDto_ = null;
        }
        return playerDtoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto)
    }

    static {
      defaultInstance = new LoginResultDto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.shadowgame.rpg.modules.protocol.dto.player.LoginResultDto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadowgame_rpg_modules_protocol_dto_player_LoginResultDto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_shadowgame_rpg_modules_protocol_dto_player_LoginResultDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nCcom/shadowgame/rpg/modules/protocol/dt" +
      "o/player/LoginResultDto.proto\022.com.shado" +
      "wgame.rpg.modules.protocol.dto.player\032>c" +
      "om/shadowgame/rpg/modules/protocol/dto/p" +
      "layer/PlayerDto.proto\"o\n\016LoginResultDto\022" +
      "\017\n\007success\030\001 \001(\010\022L\n\tplayerDto\030\002 \001(\01329.co" +
      "m.shadowgame.rpg.modules.protocol.dto.pl" +
      "ayer.PlayerDtoB\025B\023LoginResultDto$$Gen"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_shadowgame_rpg_modules_protocol_dto_player_LoginResultDto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_shadowgame_rpg_modules_protocol_dto_player_LoginResultDto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_shadowgame_rpg_modules_protocol_dto_player_LoginResultDto_descriptor,
              new java.lang.String[] { "Success", "PlayerDto", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.shadowgame.rpg.modules.protocol.dto.player.PlayerDto$$Gen.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
