// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/shadowgame/rpg/modules/protocol/dto/ProtobufDto_PROTO.proto

package com.shadowgame.rpg.modules.protobuf.dto;

public final class ProtobufDtoPROTO {
  private ProtobufDtoPROTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtobufDtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 typeId = 1;
    /**
     * <code>optional int32 typeId = 1;</code>
     *
     * <pre>
     **
     * protobuf message类型的数字id
     * </pre>
     */
    boolean hasTypeId();
    /**
     * <code>optional int32 typeId = 1;</code>
     *
     * <pre>
     **
     * protobuf message类型的数字id
     * </pre>
     */
    int getTypeId();

    // optional bytes data = 2;
    /**
     * <code>optional bytes data = 2;</code>
     *
     * <pre>
     **
     * protobuf message的二进制数据
     * </pre>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 2;</code>
     *
     * <pre>
     **
     * protobuf message的二进制数据
     * </pre>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.shadowgame.rpg.modules.protocol.dto.ProtobufDto}
   *
   * <pre>
   **
   * protobuf对象，用类型和二进制描述一个对象
   * @author wcj10051891@gmail.com
   *字段列表:
   * //protobuf message类型的数字id
   *int typeId
   * //protobuf message的二进制数据
   *com.google.protobuf.ByteString data
   * </pre>
   */
  public static final class ProtobufDto extends
      com.google.protobuf.GeneratedMessage
      implements ProtobufDtoOrBuilder {
    // Use ProtobufDto.newBuilder() to construct.
    private ProtobufDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtobufDto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtobufDto defaultInstance;
    public static ProtobufDto getDefaultInstance() {
      return defaultInstance;
    }

    public ProtobufDto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtobufDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              typeId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_ProtobufDto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_ProtobufDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto.class, com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtobufDto> PARSER =
        new com.google.protobuf.AbstractParser<ProtobufDto>() {
      public ProtobufDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtobufDto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtobufDto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 typeId = 1;
    public static final int TYPEID_FIELD_NUMBER = 1;
    private int typeId_;
    /**
     * <code>optional int32 typeId = 1;</code>
     *
     * <pre>
     **
     * protobuf message类型的数字id
     * </pre>
     */
    public boolean hasTypeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 typeId = 1;</code>
     *
     * <pre>
     **
     * protobuf message类型的数字id
     * </pre>
     */
    public int getTypeId() {
      return typeId_;
    }

    // optional bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 2;</code>
     *
     * <pre>
     **
     * protobuf message的二进制数据
     * </pre>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes data = 2;</code>
     *
     * <pre>
     **
     * protobuf message的二进制数据
     * </pre>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      typeId_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, typeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, typeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.shadowgame.rpg.modules.protocol.dto.ProtobufDto}
     *
     * <pre>
     **
     * protobuf对象，用类型和二进制描述一个对象
     * @author wcj10051891@gmail.com
     *字段列表:
     * //protobuf message类型的数字id
     *int typeId
     * //protobuf message的二进制数据
     *com.google.protobuf.ByteString data
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_ProtobufDto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_ProtobufDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto.class, com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto.Builder.class);
      }

      // Construct using com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        typeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.internal_static_com_shadowgame_rpg_modules_protocol_dto_ProtobufDto_descriptor;
      }

      public com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto getDefaultInstanceForType() {
        return com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto.getDefaultInstance();
      }

      public com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto build() {
        com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto buildPartial() {
        com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto result = new com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.typeId_ = typeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto) {
          return mergeFrom((com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto other) {
        if (other == com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto.getDefaultInstance()) return this;
        if (other.hasTypeId()) {
          setTypeId(other.getTypeId());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shadowgame.rpg.modules.protobuf.dto.ProtobufDtoPROTO.ProtobufDto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 typeId = 1;
      private int typeId_ ;
      /**
       * <code>optional int32 typeId = 1;</code>
       *
       * <pre>
       **
       * protobuf message类型的数字id
       * </pre>
       */
      public boolean hasTypeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 typeId = 1;</code>
       *
       * <pre>
       **
       * protobuf message类型的数字id
       * </pre>
       */
      public int getTypeId() {
        return typeId_;
      }
      /**
       * <code>optional int32 typeId = 1;</code>
       *
       * <pre>
       **
       * protobuf message类型的数字id
       * </pre>
       */
      public Builder setTypeId(int value) {
        bitField0_ |= 0x00000001;
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 typeId = 1;</code>
       *
       * <pre>
       **
       * protobuf message类型的数字id
       * </pre>
       */
      public Builder clearTypeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        typeId_ = 0;
        onChanged();
        return this;
      }

      // optional bytes data = 2;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 2;</code>
       *
       * <pre>
       **
       * protobuf message的二进制数据
       * </pre>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes data = 2;</code>
       *
       * <pre>
       **
       * protobuf message的二进制数据
       * </pre>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 2;</code>
       *
       * <pre>
       **
       * protobuf message的二进制数据
       * </pre>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 2;</code>
       *
       * <pre>
       **
       * protobuf message的二进制数据
       * </pre>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.shadowgame.rpg.modules.protocol.dto.ProtobufDto)
    }

    static {
      defaultInstance = new ProtobufDto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.shadowgame.rpg.modules.protocol.dto.ProtobufDto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadowgame_rpg_modules_protocol_dto_ProtobufDto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_shadowgame_rpg_modules_protocol_dto_ProtobufDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?com/shadowgame/rpg/modules/protocol/dt" +
      "o/ProtobufDto_PROTO.proto\022\'com.shadowgam" +
      "e.rpg.modules.protocol.dto\"+\n\013ProtobufDt" +
      "o\022\016\n\006typeId\030\001 \001(\005\022\014\n\004data\030\002 \001(\014B)\n\'com.s" +
      "hadowgame.rpg.modules.protobuf.dto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_shadowgame_rpg_modules_protocol_dto_ProtobufDto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_shadowgame_rpg_modules_protocol_dto_ProtobufDto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_shadowgame_rpg_modules_protocol_dto_ProtobufDto_descriptor,
              new java.lang.String[] { "TypeId", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
